spring.application.name=forecast-api
server.servlet.context-path=/api
spring.application.version=0.0.1

# Environment configuration
spring.config.import=optional:file:.env[.properties]
supabase.url=${SUPABASE_URL}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY}

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/forecast

# Database credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA and Hibernate settings
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

# Database driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging configuration
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{25}){cyan} %clr(:){faint} %msg%n
# Production settings
# springdoc.api-docs.enabled=false
# springdoc.swagger-ui.enabled=false
# swagger url: http://localhost:8080/api/swagger-ui/index.html#/